bindPort = 7000

auth.method = "token"
auth.token = "2f1d3a0e-9b64-4b91-b76b-8cb4a2f2e5d3"

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "t7#Pz8kLm@3QvW1x"

# vhostHTTPPort = 80
# vhostHTTPSPort = 443
# subDomainHost = "frps.com"
