name: Scheduled Job Every 10 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a demo script
        run: echo "This job runs every 10 minutes."